#%RAML 1.0
title: HyperStorage API
baseUri: hb://hyperstorage
types:
  HyperStorageTransaction:
    type: object
    properties:
      transaction_id: string

  HyperStorageTransactionCreated:
    type: object
    properties:
      transaction_id: string
      path: string

  HyperStorageIndexSortOrder:
    enum: [asc, desc]

  HyperStorageIndexSortFieldType:
    enum: [text, decimal]

  HyperStorageIndexSortItem:
    type: object
    properties:
      field_name: string
      field_type?: HyperStorageIndexSortFieldType
      order?: HyperStorageIndexSortOrder

  HyperStorageIndex:
    type: object
    properties:
      index_id: string
      sort_by: HyperStorageIndexSortItem[]
      filter_by?: string
      materialize: boolean
      unique: boolean

  HyperStorageIndexNew:
    type: object
    properties:
      index_id?: string
      sort_by: HyperStorageIndexSortItem[]
      filter_by?: string
      materialize?: boolean
      unique?: boolean

  HyperStorageIndexCreated:
    type: object
    properties:
      index_id: string
      path: string

/content/{path}:
  uriParameters:
    path: string
  get:
    queryParameters:
      sort_by:
        type: string
        required: false
      filter:
        type: string
        required: false
      size:
        type: integer
        required: false
      skip_max:
        type: integer
        required: false
    responses:
      200:
  put:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  patch:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  delete:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  post:
    responses:
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  feed:put:
  feed:patch:
  feed:delete:

/transactions/{transaction_id}:
  uriParameters:
    transaction_id: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction

/indexes/{path}:
  uriParameters:
    path: string
  post:
    body:
      application/json:
        type: HyperStorageIndexNew
    responses:
      201:
        body:
          application/json:
            type: HyperStorageIndexCreated

/indexes/{path}/{index_id}:
  uriParameters:
    path: string
    index_id: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageIndex
  delete:
