#%RAML 1.0
title: HyperStorage API
baseUri: hb://hyperstorage
types:
  HyperStorageHeader:
    enum:
      - Hyper-Storage-Transaction
      - Hyper-Storage-Wait
      - Hyper-Storage-TTL
      - If-Match
      - If-None-Match
      - ETag

  HyperStorageTransaction:
    type: object
    properties:
      transaction_id: string
      path: string
      revision:
        type: number
        format: long

  HyperStorageTransactionCreated:
    type: object
    properties:
      transaction_id: string
      path: string
      revision:
        type: number
        format: long
      target: object

  HyperStorageIndexSortOrder:
    enum: [asc, desc]

  HyperStorageIndexSortFieldType:
    enum: [text, decimal]

  HyperStorageIndexSortItem:
    type: object
    properties:
      field_name: string
      field_type?: HyperStorageIndexSortFieldType
      order?: HyperStorageIndexSortOrder

  HyperStorageIndex:
    type: object
    properties:
      index_id: string
      sort_by: HyperStorageIndexSortItem[]
      filter_by?: string
      materialize: boolean

  HyperStorageIndexNew:
    type: object
    properties:
      index_id?: string
      sort_by: HyperStorageIndexSortItem[]
      filter_by?: string
      materialize?: boolean

  HyperStorageIndexCreated:
    type: object
    properties:
      index_id: string
      path: string

  HyperStorageView:
    type: object
    properties:
      template_uri: string
      filter_by?: string

  HyperStorageViewCreated:
    type: object
    properties:
      path: string

/content/{path}:
  uriParameters:
    path: string
  get:
    queryParameters:
      sort_by:
        type: string
        required: false
      filter:
        type: string
        required: false
      per_page:
        type: integer
        required: false
      skip_max:
        type: integer
        required: false
    responses:
      200:
      302:
  put:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  patch:
    body:
      application/vnd.hyperstorage-content+json:
      application/vnd.hyperstorage-content-increment+json:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  delete:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  post:
    responses:
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  feed:put:
  feed:patch:
  feed:delete:

/transactions/{transaction_id}:
  uriParameters:
    transaction_id: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction

/indexes/{path}:
  uriParameters:
    path: string
  post:
    body:
      application/json:
        type: HyperStorageIndexNew
    responses:
      201:
        body:
          application/json:
            type: HyperStorageIndexCreated

/indexes/{path}/{index_id}:
  uriParameters:
    path: string
    index_id: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageIndex
  delete:

/views/{path}:
  uriParameters:
    path: string
  put:
    body:
      application/json:
        type: HyperStorageView
    responses:
      201:
        body:
          application/json:
            type: HyperStorageViewCreated
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageView
  delete:
